# tsc doesn't support pnp
# workaround: https://next.yarnpkg.com/advanced/pnpify
# or use different node linker, eg: node-modules
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
